### ISSUE TITLE
[BUG] Unknown time zone Europe/Zurich

### ISSUE THREAD

**Issue by viktorvi** [blackcowmoo/grafana-google-analytics-datasource#101]
Unknown time zone Europe/Zurich

![image](https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/10329678/154a4786-3ce5-4bcf-831c-c2938afc8f3a)

**Comment by lcc3108** [comment]
If you write down the plug-in version and the grafana version as shown in the form below, it will be faster to check.

Could you attach the grafana log as well?

```
**Describe the bug**
A clear and concise description of what the bug is.

**Grafana Version & Plugin Version**

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

```

**Comment by lcc3108** [comment]
When I look at the log, it appears that you are using window grafana.

When I tested it, it wasn't reproduced on Linux grafana, but it's reproduced on Window grafana.

I think this is a matter of how Golang handles timezone. ([link1](https://github.com/golang/go/issues/21881) [link2](https://github.com/golang/go/issues/21881))

I think it will take some time to resolve it.
I think you should run grafana through docker in the window or something else.

**Comment by lcc3108** [comment]
Issue modification pr has been merged.(#102)
It worked properly when I tested it on the window.

Available in the nextreleases.

The release schedule is likely to be mid-December.

**Comment by lcc3108** [comment]
Plugin Published.
close the issue.
