### ISSUE TITLE
[BUG] - Duplicates in Landing Page Dimension

### ISSUE THREAD

**Issue by Shebelev** [blackcowmoo/grafana-google-analytics-datasource#104]
**Describe the bug**
When I select New Users as Metrics, First Session as Time Dimension and Landing Page as Dimension receive duplicates. Check the screenshot below. Please find a way to remove them.

**Grafana Version & Plugin Version**
0.2.3

Screenshot
<img width="1989" alt="Screenshot 2023-11-26 at 14 17 48" src="https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/68848326/86944028-23fe-4b0b-b635-276305c4cde3">

**Comment by lcc3108** [comment]
Same result value without query options or filter settings

When I tested it, it came out normal.

It seems that we need to check how the raw data comes out.

Can you attach a debug log so that I can see raw data?

**Comment by lcc3108** [comment]
I'm sorry for the late response because I'm busy at the end of the year.

I've tried it a few times, but I can't reappearance it.

I want to see the raw data.

Can you attach a debug log or send it to my e-mail?

---
In addition, I wonder if there is a special setting on the dashboard.
