### ISSUE TITLE
[BUG] - Unavailability to set a required timeframe

### ISSUE THREAD

**Issue by Shebelev** [blackcowmoo/grafana-google-analytics-datasource#105]
**Describe the bug**
When I select the time interval above in the filter it doesn't impact the dataset. I see all dates in the table, but would like to cut irrelevant days including unknown NaN which all of them have not been set in the time filter.

**Grafana Version & Plugin Version**
0.2.3

Screenshot:
<img width="1981" alt="Screenshot 2023-11-26 at 14 40 37" src="https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/68848326/afa9d7a0-271c-4fa3-9297-92411541a501">

**Comment by lcc3108** [comment]
We will investigate more about the first session date for the data to appear on the 23rd.

Is there no data for columns with NaN?
If possible, can you share the column data?
