### ISSUE TITLE
How can I get more recent data

### ISSUE THREAD

**Issue by gonzalopaniagua** [blackcowmoo/grafana-google-analytics-datasource#106]
Hello,

I set up a visualization in Grafana with different GA4 metrics, the problem is that for every visualization that I have the last data it shows it's from 10-12h ago, is there anything I need to configure in Google Analytics or Grafana to receive the most recent data?

Thanks in advance for any help 😄

**Comment by lcc3108** [comment]
Is it correct that the data is not visible for the last 9 hours when looking up with the plug-in.

I think it's been viewed well in UA, but I think it's a little different from ga4.

I looked up information in the past, but I couldn't figure out the cause.

I thought about whether I should check it separately with Realtime api, but Realtime api only provides about 60 minutes of data.

I'll take this opportunity to investigate again.

https://github.com/blackcowmoo/grafana-google-analytics-datasource/issues/63

**Comment by lcc3108** [comment]
https://support.google.com/analytics/answer/11198161?hl=en

According to Google Analytics, it takes as long as the table above to process the data.

So, there is a data gap when looking up with the api.
