### ISSUE TITLE
Support for Grafana v11

### ISSUE THREAD

**Issue by sympatheticmoose** [blackcowmoo/grafana-google-analytics-datasource#111]
Hi there 👋 

I noticed in your plugin.json you've got the [grafanaDependency](https://github.com/blackcowmoo/grafana-google-analytics-datasource/blob/master/src/plugin.json#L47) set so that it will not install in Grafana 11 so wanted to reach out to check whether this is intentional?

**Comment by petemyron** [comment]
is this project dead? Will a PR be accepted?

**Comment by Srreven** [comment]
I need this as well

Is there another datasource for google-analytics ?

**Comment by sympatheticmoose** [comment]
@lcc3108 just wanted to make sure you've seen this 🙂

**Comment by lcc3108** [comment]
I couldn't handle the issue because I had a busy day.
I am planning to support version 11 with some feature updates

**Comment by sympatheticmoose** [comment]
> I couldn't handle the issue because I had a busy day.

Hope things are getting better and calmer - thank you for this plugin ❤️

**Comment by lcc3108** [comment]
I updated the plug in for use in 9<= version < 12

We are currently requesting Grafana to review it.

**Comment by ChrizC** [comment]
Is there any update on this? It's been with Grafana to review for over a month. Is it just Grafana themselves being slow to review it?

**Comment by sympatheticmoose** [comment]
Reviews can be a back and forth process - we're working together to ensure the new version works well for everyone

**Comment by lcc3108** [comment]
No, the review has been conducted and there are still modifications to be made.
(Grafana will fix the version compatibility part.)

The reason for the delay is that I traveled to Europe for three weeks.

I didn't modify the plug-in during the trip.

After the trip, I couldn't handle it because of the things I was behind and jet lag.

**Comment by lcc3108** [comment]
0.2.2-> 0.3.0 version upgrade is being discussed due to compatibility issues (for sharing)

**Comment by lcc3108** [comment]
Plugin Published.
close the issue.
