### ISSUE TITLE
Question. How to collect data from Google Analytics aggregated ...

### ISSUE THREAD

**Issue by 4erdenko** [blackcowmoo/grafana-google-analytics-datasource#116]
How to collect data from Google Analytics aggregated by month, for example, to get results by month/day/year?

**Comment by 4erdenko** [comment]
I mean its return data only per day in period. I want to get this metrics in total period, because sum of days will be different, because of google ga logics.

**Comment by lcc3108** [comment]
query mode : table
metrics : active users
dimension : month

Please set it up as above


![image](https://github.com/user-attachments/assets/bb3331e7-d714-49b3-8fc2-0d99b3ebb674)

**Comment by lcc3108** [comment]
Additionally, the aggregation feature is supported by google analytics api, but it is not currently supported by the plug in, so it is not available.

**Comment by lcc3108** [comment]
There is no response, so I will end it.
If you need it, please open it later
