### ISSUE TITLE
[FEATURE]API requirement is missing on README

### ISSUE THREAD

**Issue by enes1004** [blackcowmoo/grafana-google-analytics-datasource#122]
**Is your feature request related to a problem? Please describe.**

README is not clear on API specifications. Google Analytics Admin API and Google Analytics Data API is required, but not included in the installation instructions.

**Describe the solution you'd like**

Edit on the README to include Google Analytics Admin API and Google Analytics Data API is required, but not included in the installation instructions.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by lcc3108** [comment]
I updated the Grafana plug-in page settings page to change according to the version, but not the GitHub README.

I'll change it.

Thank you for the information.
