### ISSUE TITLE
[BUG] When giving the json file and testing it, it shows "invalid config"

### ISSUE THREAD

**Issue by nikhil-sarda** [blackcowmoo/grafana-google-analytics-datasource#52]
**Describe the bug**
I followed the exact way of getting the JWT file

**Grafana Version & Plugin Version**
Grafana 8.3.0

**To Reproduce**
1. After downloading the JWT file
2. I dragged and dropped in Grafana
3. Clicked on the save and test button
4. This is the error I get

![WhatsApp Image 2022-06-30 at 2 12 40 PM](https://user-images.githubusercontent.com/51774873/176635057-39029d32-3649-4dc5-a2e4-60ec8187845b.jpeg)

**Additional context**
Could you help me with it as I followed each step and tried it twice already?

**Comment by lcc3108** [comment]
invalid config message when below
- ga api(reporting v4, analytics v3)  client create fail
- ga api get ga porfiles 

Additional grafana logs are required.

For the plugin log, please find and paste the line logger=plugin.blackcowmo-googleanalytics-datasource

If you want to be more certain, you can adjust the log level and attach the log above.

**Comment by lcc3108** [comment]
Add FAQ.md
https://github.com/blackcowmoo/grafana-google-analytics-datasource/blob/master/FAQ.md
