### ISSUE TITLE
[VERSION] Support Grafana v9.3.2

### ISSUE THREAD

**Issue by EvsenevDev** [blackcowmoo/Grafana-Google-Analytics-DataSource#59]
Hi, is there any change to add support for Grafana v9.3.2?

**Comment by imReker** [comment]
It was already supported last year, see https://github.com/blackcowmoo/Grafana-Google-Analytics-DataSource/pull/53
But seems like the owner didn't survive in the Covid-19 epidemic in Korean.

**Comment by AsianDesignMajor** [comment]
@imReker are you serious, the developer DIED of COVID?

I guess we can't give him a hard time about his lack of responsiveness then.

I wish I knew enough to modify it myself, but I'm not there yet.

**Comment by lcc3108** [comment]
#50 duplicate
