### ISSUE TITLE
Direct traffic not in the list

### ISSUE THREAD

**Issue by jensolsson** [blackcowmoo/Grafana-Google-Analytics-DataSource#60]
Nice plugin.

But I am missing Direct traffic.
We have:
- Organic Searches
- Clicks

But how can I also graph direct traffic?

**Comment by lcc3108** [comment]
Hello. @jensolsson
My reply is very late.
I don't know everything about Google Analytics.

You can use medium when you check the possible metrics and dimensions in the url below.
https://www.googleapis.com/analytics/v3/metadata/ga/columns?pp=1
