### ISSUE TITLE
Grafana 10 support

### ISSUE THREAD

**Issue by tolzhabayev** [blackcowmoo/Grafana-Google-Analytics-DataSource#62]
Hello 👋 

Just letting you know that Grafana 10 is coming out soon and your `grafanaDependency` is currently set to not support it. This means customers that will get Grafana 10 will not be able to use your plugin.

You can test your plugin compatibility using the latest Grafana 10 `grafana/grafana-dev` [docker images](https://hub.docker.com/r/grafana/grafana-dev/tags?page=1&name=10.0.0)

https://github.com/blackcowmoo/Grafana-Google-Analytics-DataSource/blob/44a7b8caf271c6eba72145bcb3fd5354e5b2acec/src/plugin.json#L47

**Comment by lcc3108** [comment]
We are discussing the upper version when submitting the plug-in.

The current situation will be decided after testing in grafana 10.

**Comment by lcc3108** [comment]
plugin published.
support grafana version <11
