### ISSUE TITLE
Analytics data not showing in the Grafana panel 

### ISSUE THREAD

**Issue by h-pcode** [blackcowmoo/grafana-google-analytics-datasource#65]
Hi I have completed all the required steps like Created JWT  token from gcp side and added permission to the service account created , then upload the JWT to grafana side but somehow whenever I am trying to see  the data by inserting the metrics and dimensions it is showing that "Field request.dimensions.name is required., badRequest" and sometimes "Fail query" error="failed to read query: error reading query: json: cannot unmarshal object into Go struct field QueryModel.dimensions of type []string" and sometimes this  Error 400: Selected dimensions and metrics cannot be queried together., badRequest". Can you please guide me on this.

**Comment by lcc3108** [comment]
Please submit the issue according to the [bug report format](https://github.com/blackcowmoo/grafana-google-analytics-datasource/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=%5BBUG%5D)
need more infomation

>Error 400: Selected dimensions and metrics cannot be queried together., badRequest".

This error message has an option that cannot be used together between metric, time dimension, and dimension.
The current plug-in lists the available metrics, dimensions, but there is no logic to verify.

**Comment by lcc3108** [comment]
The current 0.1.5 does not support GA4.
We are working on GA4 support at the branch at the [link.](https://github.com/blackcowmoo/grafana-google-analytics-datasource/pull/64)

However, even if the branch is merged, it will take time to submit it to Grafana and approve it.
We need a test
