### ISSUE TITLE
[FEATURE] Support custom metrics and dimensions

### ISSUE THREAD

**Issue by lcc3108** [blackcowmoo/grafana-google-analytics-datasource#70]
**Is your feature request related to a problem? Please describe.**
https://github.com/blackcowmoo/grafana-google-analytics-datasource/issues/54#issuecomment-1597157310
Is support for Event Scope Custom Metrics present already / can it be added? I cannot find it in the metrics picker

![image](https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/84960805/8df34d92-c8f1-4380-a58a-bbdea16f0676)

_Originally posted by @aa-matthias in https://github.com/blackcowmoo/grafana-google-analytics-datasource/issues/54#issuecomment-1597157310_
            
**Describe the solution you'd like**
Get metrics with propertyId

**Describe alternatives you've considered**

**Additional context**

**Comment by lcc3108** [comment]
@aa-matthias 
I checked that custom metrics and dimensions currently working.

However, it was not sufficiently tested in UA and GA.
If you want to test it first, use the following branch

#69 or branch feature/backend/support-custom-metric-dimension

**Comment by aa-matthias** [comment]
Hi @lcc3108 - i would be happy to test, but it looks like the CI Action is not storing the Artefacts of the build job. Is it possible to get a plugin.zip of the package? Thanks!

**Comment by aa-matthias** [comment]
@lcc3108 do you know when Release 0.2.1 will be published in the grafana Plugin Marketplace?

**Comment by aa-matthias** [comment]
thanks, ok

**Comment by lcc3108** [comment]
0.2.1 released

**Comment by aa-matthias** [comment]
Checking out Release 0.2.2 I can now pick Custom Metrics in the Query Builder 🚀 - returned values are null but same query works in GA4 Query Explorer

![image](https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/84960805/d5e33696-8331-4319-8aa7-becd6716cae4)

this seems to be a type config issue based on the warnings i get

![image](https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/84960805/f9b819c2-1303-4d17-8016-7dad4b2b9fc6)

![image](https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/84960805/356e6b44-30d9-4351-ba37-1a93d039bb5e)

**Comment by lcc3108** [comment]
@aa-matthias 
I will create a new issue based on what you reported.

Additionally, could you give me a brief explanation or a link so that I can set the custom metric the same?

**Comment by aa-matthias** [comment]
Sure - custom metrics need to be defined within the GA4 propery. RunReportResponse will then include information about the data type of the custom metric. Possible types can be seen in the docs:

https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/MetricType?hl=en

I would say the type needs to be considered when interpreting / transforming the response - looks like currently the grafana-google-analytics-datasource plugin tries to interpret the values as datetime fields.

in our case the metric is of type TYPE_MILLISECONDS
