### ISSUE TITLE
[FEATURE] Real Time dashboard, It is possible?

### ISSUE THREAD

**Issue by yititofer** [blackcowmoo/grafana-google-analytics-datasource#74]
**Is your feature request related to a problem? Please describe.**
Request: It is possible to obtain the number of users in real time and be able to generate a board with several sites...

**Describe the solution you'd like**
The Google Analytics plugin is using the runReport API to load data.
Since there is a runRealtimeReport API, it could be used in some option to use that API.

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by lcc3108** [comment]
According to the document, it is an api that allows data inquiry within the 30~60min

I don't know if I want to query in combination with existing functions or if I need to separate the Real-Time Query feature separately.

If you have any suggestions, please leave a comment

Thank you.

**Comment by lcc3108** [comment]
[According to the document,](https://developers.google.com/analytics/devguides/reporting/data/v1/quotas) runReport (currently in use) and runRealtimeReport (the feature requested in the issue) have different quotas.

So I think the quota problem will be separated.

I think it will proceed in a separate way from the previous one.

**Comment by lcc3108** [comment]
Plugin Published.
close the issue.
