### ISSUE TITLE
[BUG] How to remove Time Dimension?

### ISSUE THREAD

**Issue by Shebelev** [blackcowmoo/grafana-google-analytics-datasource#77]
In order to build a report which is reflecting the number of visitors grouped by 'Landing Page + query string', I would like to use only one dimension 'Landing Page + query string' with the timeframe that I can set in the time panel in the top right corner.

But in the current configuration, Time Dimension choosing is mandatory. So I'm getting date rows and columns with Landing Pages, please check out the following screenshot:
<img width="2139" alt="image" src="https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/68848326/ec12ecd3-7e5b-44df-8bf6-3bedeef2ac80">

I suggest getting the table as we see on Google Analytics. Rows are dimensions, columns are metrics. With options to get rid of Time Dimension.
<img width="816" alt="image" src="https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/68848326/5dc79471-49c2-49c5-ae43-954bdd217fea">

Please, let me know if it is possible to implement or fix it in the upcoming days.

**Comment by lcc3108** [comment]
We need to test it, but it seems possible to implement it.
Previously, time dimensions were required because it was based on the use of grafana graphs.

**Comment by Shebelev** [comment]
I would really appreciate it if you could do it soon. Again, my goal is to get the table with 'Landing Page + query string' dimension as the first column and metrics such as Active Users, Sessions and etc in the following columns the same as you can see on the screenshot from GA below:
<img width="489" alt="image" src="https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/68848326/6663151d-f71f-4a57-b78a-1247d2c858ea">

Let me know if you have any questions.

**Comment by Shebelev** [comment]
Nice to see this in your TODO list!

**Comment by Shebelev** [comment]
@lcc3108 hi, dude! Would you tell me the estimated time when you will be able to make this work?
Thanks in advance!

**Comment by lcc3108** [comment]
@Shebelev 

It is difficult to answer the estimated time.
Even if the development is finished now, i don't know how long it will take until the grafana plugin update process.

One thing I can say is that I just started working on it.

**Comment by lcc3108** [comment]
<img width="1636" alt="image" src="https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/38449269/19abe601-b483-4925-afd1-120f1d2119a5">

I think the backend work is pretty much done.
However, the data verification part and front-end work are left.

We are planning to create a separate UI because we can only scope it by date when looking up data in GA. (Maybe...)

**Comment by Shebelev** [comment]
Hi, awesome! It looks just like we needed. I'm excited when you finalize this update. Thanks!

**Comment by Shebelev** [comment]
@lcc3108 is the plugin available now? or can this issue be on our end? Thanks for what you do!

![Image](https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/68848326/347bc483-eb25-44f5-bd35-ce8cdb712cb7)

**Comment by lcc3108** [comment]
@Shebelev 
0.2.1 has a bug, so I fixed it as 0.2.2.

Can you tell me the version information?

**Comment by Shebelev** [comment]
@Shebelev 
We updated Grafana, and all works but I see the same. It still requires me to choose the period of time. When I do it, I receive divided data by the second dimension 

![Image](https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/68848326/c4927ea3-ed78-44a8-9da9-364a9d32ae6c)



![Image](https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/68848326/45b68c2c-7724-43c7-be70-7f2d30340bbf)

**Comment by lcc3108** [comment]
@Shebelev 
The feature of the current issue is released in 0.2.3.

Plug-in updates have been submitted and will be released after a grafana review.
