### ISSUE TITLE
Plugin health check failed

### ISSUE THREAD

**Issue by asil-x** [blackcowmoo/grafana-google-analytics-datasource#81]
I have follow and double check all introduction step but still receive plugin health check failed

Grafana a v10.1.0 & Google Analytics v0.2.0

here is my log: 
2023-08-31 09:23:13 logger=context userId=1 orgId=1 uname=admin t=2023-08-31T07:23:13.716521425Z level=error msg="Plugin unavailable" error="plugin unavailable" remote_addr=172.17.0.1 traceID=
2023-08-31 09:23:13 logger=context userId=1 orgId=1 uname=admin t=2023-08-31T07:23:13.716696498Z level=error msg="Request Completed" method=GET path=/api/datasources/uid/e7ffe070-f3c7-458f-9eb2-4fed4471972e/health status=503 remote_addr=172.17.0.1 time_ms=1 duration=1.327593ms size=45 referer=http://localhost:3000/connections/datasources/edit/e7ffe070-f3c7-458f-9eb2-4fed4471972e handler=/api/datasources/uid/:uid/health

<img width="545" alt="image" src="https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/77730298/63cf0fd3-f2a1-49b2-b071-df752c0ac67f">

Google Analytics API and Google Analytics Reporting API are both installed:
<img width="814" alt="image" src="https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/77730298/a2da870d-5aa2-4e39-a43f-ff1bc48ec794">

**Comment by asil-x** [comment]
> You need to attach the debug log.
> 
> It is estimated that there is a problem with the following link. [#51 (comment)](https://github.com/blackcowmoo/grafana-google-analytics-datasource/issues/51#issuecomment-1691386878)

I tried but still same result, here is my log
2023-08-31 10:02:52 logger=context userId=1 orgId=1 uname=admin t=2023-08-31T08:02:52.530606107Z level=error msg="Request Completed" method=GET path=/api/datasources/uid/d4721ac7-2d74-4bad-bf05-3071c2f5a1e5/health status=500 remote_addr=172.17.0.1 time_ms=12930 duration=12.930048263s size=53 referer=http://localhost:3000/connections/datasources/edit/d4721ac7-2d74-4bad-bf05-3071c2f5a1e5 handler=/api/datasources/uid/:uid/health
2023-08-31 10:02:52 logger=plugin.blackcowmoo-googleanalytics-datasource t=2023-08-31T08:02:52.530451579Z level=error msg="plugin process exited" path=/var/lib/grafana/plugins/blackcowmoo-googleanalytics-datasource/gpx_blackcowmoo-googleanalytics-datasource_linux_amd64 pid=54 error="exit status 2"
2023-08-31 10:02:52 logger=plugin.blackcowmoo-googleanalytics-datasource t=2023-08-31T08:02:52.879560581Z level=info msg=Profiler enabled=false

**Comment by lcc3108** [comment]
The log you attached is not a "debug" log.
However, it seems to be the same issue as #51.

I'm releasing version 0.2.1 to patch this issue and I'm waiting for your Grafana approval.

**Comment by moovs** [comment]
@lcc3108 maybe you remember on verion 0.2.0 I gor error Plugin Health Check Failed, after you updated to 0.2.1 version I tried this version and this error gone, but I received a new error: 
<img width="580" alt="Screenshot 2023-09-01 at 10 24 02" src="https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/33874837/71471431-4b65-4def-afa9-9ccd120f02bc">

Whay do you think about it? Is it problem with my profile or something else?

**Comment by lcc3108** [comment]
@moovs 
Which version of health check did you do, UA(GA3) or GA4?

Please attach a debug log to check the problem.

**Comment by moovs** [comment]
Yes, it's UA profile here my debug logs:
```
logger=plugin.blackcowmoo-googleanalytics-datasource t=2023-09-01T08:32:34.455454371Z level=error msg="CheckHealth: Not Exist Valid Profile"
logger=context userId=1 orgId=1 uname=superadmin t=2023-09-01T08:32:34.455662199Z level=info msg="Request Completed" method=GET path=/api/datasources/uid/JbvB1dkIk/health status=400 remote_addr=172.25.0.1 time_ms=173 duration=173.008477ms size=67 referer=http://grafana_domain/datasources/edit/JbvB1dkIk handler=/api/datasources/uid/:uid/health
```

**Comment by lcc3108** [comment]
@moovs 
UA has a structure of account -> webproperty -> profile.
You must have a **profile** to query the data.


```
logger=plugin.blackcowmoo-googleanalytics-datasource t=2023-09-01T08:36:26.667933897Z level=debug msg="UA GetAccountSummaries raw accounts" debug="[map[id:225841363 kind:analytics#accountSummary name:Default Account for Firebase]]"
logger=plugin.blackcowmoo-googleanalytics-datasource t=2023-09-01T08:36:26.668014326Z level=debug msg="UA GetAccountSummaries accounts" debug=null
```

According to the log, only one account without webproperty and profile 
The error message "Not Exist Valid Profile" was responded accordingly.


Based on the past post (https://github.com/blackcowmoo/grafana-google-analytics-datasource/issues/51#issuecomment-1689817760), all accounts are as follows.

```
{
  "kind": "analytics#accountSummaries",
  "username": "****",
  "totalResults": 4,
  "startIndex": 1,
  "itemsPerPage": 10,
  "items": [
    {
      "id": "2*****",
      "kind": "analytics#accountSummary",
      "name": "Default Account for Firebase",
      "webProperties": []
    },
    {
      "id": "2******",
      "kind": "analytics#accountSummary",
      "name": "***",
      "webProperties": []
    },
    {
      "id": "2***",
      "kind": "analytics#accountSummary",
      "webProperties": [
        {
          "kind": "analytics#webPropertySummary",
          "id": "UA-2******",
          "name": "******",
          "internalWebPropertyId": "2******",
          "level": "STANDARD",
          "websiteUrl": "http://1******",
          "profiles": [
            {
              "kind": "analytics#profileSummary",
              "id": "2*******",
              "name": "*",
              "type": "WEB"
            }
          ]
        }
      ]
    },
  ]
}
```
It seems that the permission of the service account placed in grafana can only be inquired about the first item.
You must give permission to the Graffana service account on the Google Analytics page in the array of items[2].

**Comment by moovs** [comment]
man I did all from your manual))

**Comment by lcc3108** [comment]
Yes, you proceeded according to the manual.
However, in the Google Analytics Setting section, only some accounts (GA accounts, not Google accounts) were conducted.

- goto https://analytics.google.com/
![image](https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/38449269/0b23358d-b726-4ab2-9963-d651ae71a11e)
- Proceed with Google Analytics Setting for each Analytics account.

**Comment by moovs** [comment]
Do you mean that I should setup all of my google analytics accounts according your manual? Not only one account that I want to use in my grafana integration?

**Comment by lcc3108** [comment]
@moovs 
Generate JWT file can be done only once.
In the process above, one service account will be created.

You must give View permission to your service account by account in Google Analytics.
However, you only need to do an account with a profile.(This is because you need a profile to accumulate data.)
In your case, there are three UA accounts, but only one profile exists.

In other words, currently, data is accumulated only in the account below, so you only need to do the account below.

```
    {
      "id": "2***",
      "kind": "analytics#accountSummary",
      "webProperties": [
        {
          "kind": "analytics#webPropertySummary",
          "id": "UA-2******",
          "name": "******",
          "internalWebPropertyId": "2******",
          "level": "STANDARD",
          "websiteUrl": "http://1******",
          "profiles": [
            {
              "kind": "analytics#profileSummary",
              "id": "2*******",
              "name": "*",
              "type": "WEB"
            }
          ]
        }
      ]
    },
```

---

In my case, I have two Google Analytics accounts
- Default Accounts for Firebase
- test

![image](https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/38449269/74530367-b562-4727-abce-7614729abff8)

You must grant permission to each account.
It's like the following picture.
![image](https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/38449269/8bb34280-7495-4071-ab32-50ba1b4fea14)

<img width="868" alt="image" src="https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/38449269/da35daba-75da-4c8c-aae9-824859012cdb">


Then you can look it up on Grafana as follows.

<img width="285" alt="image" src="https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/38449269/ad6b2ae1-a672-495b-990b-ec39a0039215">

---

In your case, only 'Default Account for Firebase' has permissions that do not currently have a profile created. (Checked by log)

From version 0.2.1, you will get an error saying that you don't have the right account because you have excluded accounts that don't have a profile (data can't be retrieved) from the list.

**Comment by lcc3108** [comment]
@asil-x 
0.2.1 has been released.

If the same problem occurs in that version, please open this issue again
