### ISSUE TITLE
[BUG]: GoggleAnalytics Datasource broken in 0.2.1

### ISSUE THREAD

**Issue by blaketwist** [blackcowmoo/grafana-google-analytics-datasource#82]
**Describe the bug**
I just updated from 0.2.0 to 0.2.1. The old Google Analystics datasource is not recognized anymore. When I create a new datasource, Grafana show the snackbar "Datasource added". I also see it in the list. When I click on it, I get a blank screen, with only the info: "Type: Google Analytics" and the options to delete the datasource and go back. I cannot edit it, nor test it - see image.

![Screenshot 2023-09-04 at 16 52 01](https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/15229892/0d3b9e68-92be-4570-8039-8cbb7aed34e7)

**Grafana Version & Plugin Version**
0.2.1

**Expected behavior**
I expect to be able to edit + test the datasource.

**Comment by blaketwist** [comment]
`grafana-server --version: Version 9.5.8 (commit: 4c140fd26e, branch: HEAD)`

It happens for me when I create a datasource both ways: either directly, or via the plugin. The result is always a 404:
`GET https://<server>/public/plugins/blackcowmoo-googleanalytics-datasource/module.js?_cache=0.2.1 404`

From developer tools/network:
`module.js?_cache=0.2.1`: `{message: "Plugin file not found"}`

Does this help? 
I can't upload screenshots at the moment. I'll try in a separate comment.

**Comment by blaketwist** [comment]
I set up a Grafana 10 Server to see if the plugin works there, but I cannot install it any more via the Grafana UI. Did you disable it?

**Comment by lcc3108** [comment]
No, it is not disabled.
Maybe the Grapana team disabled it.

The query editor has determined the cause, but has not yet determined the setup screen.

I think I'll have to check it's.

**Comment by lcc3108** [comment]
When I tested it on Grafana Cloud, it looked the same.

Maybe it happened when I modified the case space for plugins.

Uninstall and reinstall the plug-in completely
In my case, reinstalling the plug-in worked well.

**Comment by blaketwist** [comment]
With version 0.2.2 it now works again. Thank you.
