### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rgparkins** [blackcowmoo/grafana-google-analytics-datasource#83]
**Describe the bug**

I am not sure this is a bug rather something I have missed on configuration but I have followed the instructions for GA4 data source.

When creating a dashboard with GA4 I get an exception and cant run a query

**Grafana Version & Plugin Version**

0.2.1

**To Reproduce**

I have performed the instruction for setting up google analytics with grafana plugin, 
**please note in step 5 I can only add a user and the additional 8th step and setting permissions I dont have in GA4** 
I have tested the connection and everything is testing as success.
I then start a dashboard and immediately an exception is raised

**Expected behavior**

I can start a query

**Screenshots**

attached

**Additional context**

These are the logs I see

``` 2023-09-06 22:05:59 logger=plugin.blackcowmoo-googleanalytics-datasource t=2023-09-06T22:05:59.71174033Z level=error msg="Fail query" error="Required AccountID"

     2023-09-06 22:05:59 logger=plugin.blackcowmoo-googleanalytics-datasource t=2023-09-06T22:05:59.711710955Z level=error msg=Query error="Required AccountID"```

**Comment by lcc3108** [comment]
There's a null check missing in the query editor
I'll fix it.

**Comment by lcc3108** [comment]
The 0.2.0 version is available through the command below until the update.

```
grafana-cli plugins install blackcowmoo-googleanalytics-datasource 0.2.0
```

and grafana restart

**Comment by rgparkins** [comment]
Thanks you @lcc3108, I am using grafana cloud atm is there a way to update on there do you know?

**Comment by lcc3108** [comment]
@rgparkins 
You have to choose from the list of pickers above.


<img width="792" alt="image" src="https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/38449269/72baf3ae-f5df-4cf3-a986-fe1912162cdd">

**Comment by rgparkins** [comment]
@lcc3108 many thanks, I have the new one working great 👍 just couldn;t see the wood for the trees.. 🙏

**Comment by lcc3108** [comment]
I think it's probably because of the bad UI.
I will close the issue.
