### ISSUE TITLE
Metric Data Type TYPE_MILLISECONDS	 Conversion Bug

### ISSUE THREAD

**Issue by lcc3108** [blackcowmoo/grafana-google-analytics-datasource#85]
Checking out Release 0.2.2 I can now pick Custom Metrics in the Query Builder 🚀 - returned values are null but same query works in GA4 Query Explorer

![image](https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/84960805/d5e33696-8331-4319-8aa7-becd6716cae4)

this seems to be a type config issue based on the warnings i get

![image](https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/84960805/f9b819c2-1303-4d17-8016-7dad4b2b9fc6)

![image](https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/84960805/356e6b44-30d9-4351-ba37-1a93d039bb5e)

_Originally posted by @aa-matthias in https://github.com/blackcowmoo/grafana-google-analytics-datasource/issues/70#issuecomment-1711756483_

**Comment by lcc3108** [comment]
```
	// Type: The metric's data type.
	//
	// Possible values:
	//   "METRIC_TYPE_UNSPECIFIED" - Unspecified type.
	//   "TYPE_INTEGER" - Integer type.
	//   "TYPE_FLOAT" - Floating point type.
	//   "TYPE_SECONDS" - A duration of seconds; a special floating point
	// type.
	//   "TYPE_MILLISECONDS" - A duration in milliseconds; a special
	// floating point type.
	//   "TYPE_MINUTES" - A duration in minutes; a special floating point
	// type.
	//   "TYPE_HOURS" - A duration in hours; a special floating point type.
	//   "TYPE_STANDARD" - A custom metric of standard type; a special
	// floating point type.
	//   "TYPE_CURRENCY" - An amount of money; a special floating point
	// type.
	//   "TYPE_FEET" - A length in feet; a special floating point type.
	//   "TYPE_MILES" - A length in miles; a special floating point type.
	//   "TYPE_METERS" - A length in meters; a special floating point type.
	//   "TYPE_KILOMETERS" - A length in kilometers; a special floating
	// point type.
```
ga data type

**Comment by aa-matthias** [comment]
@lcc3108 - thanks for fixing that one! it's still not showing up on grafana plugin page - is the review still pending?

**Comment by lcc3108** [comment]
> @lcc3108 - thanks for fixing that one! it's still not showing up on grafana plugin page - is the review still pending?

Yes, I just submitted a revision and I'm waiting for a review.

**Comment by aa-matthias** [comment]
thanks, working now! i had to force refresh the browser to ensure the query mode (time series / table) selector was shown and added to existing panels. once switched to table and back to time series everything is working now... :)
