### ISSUE TITLE
Hi! There not FiltersExpression, we try to filter data and got nothing. Seems like not working

### ISSUE THREAD

**Issue by FDCrash** [blackcowmoo/grafana-google-analytics-datasource#86]
In this place(for GA4);
https://github.com/blackcowmoo/grafana-google-analytics-datasource/blob/863f375cce3df5ff8d483f46d2cb7dab5d44b5a7/pkg/gav4/client.go#L93

But for GA3 it exist: 
https://github.com/blackcowmoo/grafana-google-analytics-datasource/blob/863f375cce3df5ff8d483f46d2cb7dab5d44b5a7/pkg/gav3/client.go#L88

Could you please describe how we can use **FiltersExpression** if this is normal behavior?

**Comment by lcc3108** [comment]
#76 duplicate
