### ISSUE TITLE
[BUG] Improvement of preparations

### ISSUE THREAD

**Issue by axi92** [blackcowmoo/grafana-google-analytics-datasource#92]
**Describe the bug**
I have issues finding the right settings with the preparations.

**Grafana Version & Plugin Version**
Grafana v10.1.1 (0cfa76b22d)
Plugin: 0.2.2

**To Reproduce**
1. Try to follow setup instructions

On step 9 I am not sure if I have done this the right way:
It shows me this screen below, is it now setup correctly for step 9?
![image](https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/1394837/16252b4f-b8ff-4d89-aeb0-691e075f5610)

On step 10 how do I enable access for my GA data?
It looks like this:
![image](https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/1394837/443b4b94-3b74-42cd-a9d0-d426b3e2b231)

**Expected behavior**
Explain with the exact text labels that I have to click or provide screenshots how to handle the setup.

**Screenshots**
See above

**Additional context**

**Comment by lcc3108** [comment]
Hyperlinks have been placed on links that correspond to instructions.
Click the link and activate it.
Step 10 is the same.

According to the uploaded screenshot, you appear to have been authorized for UA (GA3).
Go to the link below if you want to know exactly
https://console.cloud.google.com/apis/dashboard
---
>Explain with the exact text labels that I have to click or provide screenshots how to handle the setup.


If you include screenshots in the settings page, the settings page will be too long.

However, it may be difficult to set up, so we will consider creating a link after adding a setup method including a screenshot.

**Comment by axi92** [comment]
I followed your link but I don't know what to look for there. Am I correctly authorized?
![image](https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/1394837/16c5da4f-22f2-4a10-9ff8-fb9af5de20c6)

Screens on the settings page will be too long that is true. Maybe use a readme or the wiki on github for a more detailed guide?

**Comment by lcc3108** [comment]
Do you know the versions UA and GA of Google Analytics.
UA doesn't build up data from 2023-07-01 (probably).

```
9. Open the[Google Analytics API(UA)](https://console.cloud.google.com/apis/library/analytics.googleapis.com)in API Library and enable access for your account
10. Open the[Google Analytics Reporting API(UA)](https://console.cloud.google.com/marketplace/product/google/analyticsreporting.googleapis.com)in API Library and enable access for your Analytics Data
```
According to the screenshot, you can see that 'Google Analytics API' and 'Google Analytics Reporting API' are activated.
The name of the menu is enabled api

**Comment by axi92** [comment]
Sry I dont know where to find the version of UA or GA. I never used it.

But since both links say that the api is enabled I guess its ok configured?

Now I have a question on the "Google Analytics Setting"
Step 3: Click Account User Management on the Account Tab

I cant find "Account User Management" or did they rename it to Account Access Management?

![image](https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/1394837/d329923b-b844-4241-b1f5-2c998a73c013)

Maybe the error code from the plugin says something? I get: 
CheckHealth: Not Exist Valid Profile

**Comment by lcc3108** [comment]
> Sry I dont know where to find the version of UA or GA. I never used it.

I recommend you try Googling.
If the data is being accumulated after 07/01/2023, it should be set as GA.

>I cant find "Account User Management" or did they rename it to Account Access Management?

yes

>Maybe the error code from the plugin says something? I get:
CheckHealth: Not Exist Valid Profile

You do not have access to an account or no accounts have accumulated data.

**Comment by axi92** [comment]
I am really sorry but I have no time right now to debug the confusing google permissions.
Maybe I get back at you at a later time. You can close the issue for now =)
Thank you for your help!
