### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by emp-kosh** [blackcowmoo/grafana-google-analytics-datasource#94]
**Grafana Version & Plugin Version**
Latest
**To Reproduce**
1. Go to 'the url on grafana cloud to add a jwt token'
2. Click on 'add the token when you get after you download the plugin successfully.'
3. Scroll down to 'add a new dashboard and select google analytics as the source'
4. See error 'Required AccountID
(Trace ID: 2e6e9ffbd5509665fa95d9206a854e17)'

**Expected behavior**
Data supposed to appear.

**Screenshots**
![image](https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/111253014/a5af7d91-42a7-4600-ae03-2943f2e0b8f7)

**Comment by emp-george** [comment]
This is not a bug, but a fault on the developers end. I will not be helping you to solve it
