### ISSUE TITLE
Last 30 days timepicker incorrect

### ISSUE THREAD

**Issue by reuvygroovy** [blackcowmoo/grafana-google-analytics-datasource#99]
**Describe the bug**
When choosing the "last 30 days" (or the like) in the timepicker the start date isn't processed correctly, but instead shows 12 hours ago. But when I manually select the time period in the panel by using "hardcoded" dates, it works. Alternatively, when I use the "Explore" mode for the same panel then also the last 30 days works.

**Grafana Version & Plugin Version**
Grafana v10.0.1 (5a30620b85)
Chrome browser
We are using the latest analytics datasource/plugin version

This is how it looks in a regular panel (incorrect):
![image](https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/1325158/b6fbef3d-3e4c-4534-93a3-cb7ee8bf3f44)

But when we view the same panel in "Explore" mode it does display it accurately:
![image](https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/1325158/0f56df4d-ccd5-4fc7-ab78-8b2697ac30c2)

**Comment by lcc3108** [comment]
The plug-in only accepts requests from grafana and outputs the result value.

Depending on the settings, the plug-in can decide whether to run the query anew or not.
(However, the query is supposed to be executed when the time range is changed.)

Additionally, is it a case where the problem only occurs in my plug-in?

If that's right, could you tell me more information?
Detailed reproducible instructions or videos, etc

If not, I think we should create an issue in Grappa or Repo.

**Comment by reuvygroovy** [comment]
This only happens with your plugin. Other plugins such as MySQL datasources work just fine.

See attached video.

Uploading google_grafana.mp4…

**Comment by reuvygroovy** [comment]
Uploading google_grafana.mp4…

**Comment by reuvygroovy** [comment]
Uploading google_grafana.mp4…

**Comment by reuvygroovy** [comment]
I don't know if the vide was uploaded properly or not so let me know.

**Comment by lcc3108** [comment]
It's only appearing during upload.

Or if you send it to my email, I'll check it out.

dlacocjf32@gmail.com

**Comment by lcc3108** [comment]
Additionally, the plug-in does not appear to be up to date.

The latest version has Query mode as shown below.

Therefore, please attach the plug-in version as well.

Or please update it to see if it's resolved.

When I tested only on the latest version plug-in, it worked normally.

<img width="749" alt="image" src="https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/38449269/73e68030-ac02-4325-96ef-194ce0c67c2a">

**Comment by reuvygroovy** [comment]
Updated to the latest version but that didn’t help

**Comment by lcc3108** [comment]
I saw the video you sent me.

But it can't be reproduced.

Would it still not be renewed even if I proceed with the following?
1. Create and configure new dashboards
2. Click the Refresh button after changing the time
---
Can you share the dashboard like the picture below so that I can reproduce it?
<img width="952" alt="image" src="https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/38449269/92898e96-5e52-431a-9572-e45d748f9aaa">
<img width="379" alt="image" src="https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/38449269/16fca5dc-f61c-4087-a4b8-0ae2f0b81e45">

**Comment by reuvygroovy** [comment]
Attached export

With the time hard coded
***@***.***

With the last 30 days
***@***.***

Refresh doesn’t help

**Comment by lcc3108** [comment]
@reuvygroovy 
Dashboard json file is not attached.

**Comment by reuvygroovy** [comment]
[Uploading ABC123-1700111347882.json…]()

**Comment by reuvygroovy** [comment]
Attached. Let me know if you got it

**Comment by lcc3108** [comment]
Yes, I received it through email.

I'll check.

**Comment by lcc3108** [comment]
Remove Query options -> Relative time

Original
<img width="1491" alt="image" src="https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/38449269/173d4509-c5b5-4695-9032-57661710b809">

Fix
<img width="1496" alt="image" src="https://github.com/blackcowmoo/grafana-google-analytics-datasource/assets/38449269/d85ab59d-940c-43e0-9c77-cc9cb9ec3360">

**Comment by reuvygroovy** [comment]
Awesome! Amazing! Sorry I made such a mistake :-(
